---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app1-network-policy
spec:
  podSelector:
    matchLabels:
      name: app1
  ingress:
  - ports:
    - protocol: TCP
      port: 9999
  - from:
    - podSelector: {}
