apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app1
  namespace: iankwatts-dev
spec:
  to:
    kind: Service
    name: app1
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
