---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app2-network-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 9999
    - from:
      - podSelector: {}
